notifications:
  email: false
language: java
jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

# command to build
install:
  - gradle assemble
  - gradle build
  - gradle jar
  - gradle javadoc
  - './release.sh nightly'

# command to run tests
script:
  - gradle check

after_success: